### ISSUE TITLE
NVIDIA headless drivers do not support the container

### ISSUE THREAD

**Issue by nick008a** [selkies-project/docker-nvidia-egl-desktop#27]
```
INFO:signaling:Listening on http://0.0.0.0:8080
INFO:signaling:websocket server started
INFO:webrtc_input:Resetting keyboard modifiers.
INFO:webrtc_input:starting clipboard monitor
INFO:webrtc_input:Found XFIXES version 4.0
INFO:webrtc_input:starting cursor monitor
INFO:webrtc_input:watching for cursor changes
INFO:webrtc_input:sending clipboard content, length: 34
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selkies_gstreamer/__main__.py", line 732, in <lambda>
    loop.run_in_executor(None, lambda: gpu_mon.start())
  File "/usr/local/lib/python3.10/dist-packages/selkies_gstreamer/gpu_monitor.py", line 42, in start
    gpu = GPUtil.getGPUs()[0]
IndexError: list index out of range
INFO:signaling:Connected to ('127.0.0.1', 59490)
INFO:signaling:Registered peer '0' at ('127.0.0.1', 59490)
INFO:signaling:'0' command 'SESSION 1'
WARNING:webrtc_input:exception from fetching cursor image: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1293, sequence_number = 20, major_opcode = 138, minor_opcode = 4
INFO:signaling:'0' command 'SESSION 1'
INFO:signaling:Connected to ('172.38.0.3', 36944)
INFO:signaling:'0' command 'SESSION 1'
INFO:signaling:Registered peer '1' at ('172.38.0.3', 36944)
INFO:signaling:'0' command 'SESSION 1'
INFO:signaling:Session from '0' (('127.0.0.1', 59490)) to '1' (('172.38.0.3', 36944))
INFO:gstwebrtc_app:starting pipeline
0:00:06.375390028    60 0x55645ad7c690 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:701:gst_element_factory_make_with_properties: no such element factory "cudaupload"!
0:00:06.375402718    60 0x55645ad7c690 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:701:gst_element_factory_make_with_properties: no such element factory "cudaconvert"!
0:00:06.375430511    60 0x55645ad7c690 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:754:gst_element_factory_make_valist: no such element factory "nvh264enc"!
ERROR:main:Caught exception: 'NoneType' object has no attribute 'set_property'
INFO:webrtc_input:stopping clipboard monitor
INFO:webrtc_input:stopping cursor monitor
INFO: gst-python install looks OK
WARNING:webrtc_input:exception from fetching cursor image: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1293, sequence_number = 23, major_opcode = 138, minor_opcode = 4
INFO:webrtc_input:exiting cursor monitor
```

**Comment by ehfd** [comment]
On it in around a week... but first contact GStreamer devs at #gstreamer in the oftc.org IRC or https://matrix.to/#/#_oftc_#gstreamer:matrix.org on this, as it may be a faster solution.

**Comment by ehfd** [comment]
Thanks for the reminder. First of all, I need the conditions for your workspace. Anything special in your setup?

**Comment by ehfd** [comment]
Okay, I will check NVIDIA 535.

**Comment by ehfd** [comment]
Immediate directive is NOT to upgrade to NVIDIA 535, yet.

**Comment by ehfd** [comment]
May be related: https://github.com/selkies-project/docker-nvidia-glx-desktop/issues/41

**Comment by ehfd** [comment]
Works for me. Please reproduce on the latest container build.
https://github.com/selkies-project/docker-nvidia-egl-desktop/pkgs/container/nvidia-egl-desktop

**Comment by ehfd** [comment]
Could you try removing SYS_ADMIN and try again? Or did it work for you with that setting until 535?

**Comment by ehfd** [comment]
```
deploy:
  resources:
    reservations:
      devices:
      - capabilities: ["gpu"]
```

Just asking because I don't know; does this syntax correctly provision the GPUs?

**Comment by ehfd** [comment]
@danisla any clues?...

Continues to work for me.

**Comment by ehfd** [comment]
I believe there is something specific to your setup. I need all the relevant information about the host and stacks.

**Comment by ehfd** [comment]
nvidia-headless-535?... I think that might be one of the issues.

**Comment by ehfd** [comment]
I don't see the nvenc libraries in that package.

**Comment by ehfd** [comment]
It should be pushed if NVIDIA_DRIVER_CAPABILITIES is all or includes video.

I should add to the docs that you should not install headless drivers. Please keep open.

**Comment by ehfd** [comment]
Docs added.
